# train_model.py
"""
Train throughput prediction model for AI-driven channel selection.

Reads wireless_dataset.csv (generated by generate_dataset.py),
trains a RandomForestRegressor to predict throughput, evaluates it,
and saves the trained model to throughput_model.pkl.
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor


def metrics(y_true, y_pred):
    """Compute MAE, RMSE, and R^2 without sklearn.metrics."""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    mae = float(np.mean(np.abs(y_true - y_pred)))
    rmse = float(np.sqrt(np.mean((y_true - y_pred) ** 2)))

    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot != 0 else 0.0

    return mae, rmse, r2


def main():
    # Load dataset
    df = pd.read_csv("wireless_dataset.csv")

    # Features used by channel_selector.py
    feature_cols = ["channel", "rssi", "snr", "interference", "load"]
    target_col = "throughput"

    # Basic validation
    missing = [c for c in feature_cols + [target_col] if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in dataset: {missing}")

    X = df[feature_cols]
    y = df[target_col]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=695
    )

    # Train model
    model = RandomForestRegressor(
        n_estimators=300,
        random_state=695,
        n_jobs=-1
    )
    model.fit(X_train, y_train)

    # Evaluate
    preds = model.predict(X_test)
    mae, rmse, r2 = metrics(y_test, preds)

    print("Model: RandomForestRegressor")
    print("Test MAE:", round(mae, 3))
    print("Test RMSE:", round(rmse, 3))
    print("Test R^2:", round(r2, 3))

    # Save
    joblib.dump(model, "throughput_model.pkl")
    print("Saved model to throughput_model.pkl")


if __name__ == "__main__":
    main()
